### ISSUE TITLE
ClientAuthenticationError when fetching job results with Workspace.list_jobs

### ISSUE THREAD

**Issue by guenp** [microsoft/qdk-python#190] opened 2021-11-29 07:24 UTC
**Bug**

When fetching the job results after getting a job via `Workspace.list_jobs`, the client throws an error:

```
jobs = workspace.list_jobs("My_Job_")
job = jobs[0]
job.get_results()
```

```
ClientAuthenticationError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:43efab21-401e-0026-36f1-e4a06d000000
Time:2021-11-29T07:21:40.4146303Z
ErrorCode:AuthenticationFailed
authenticationerrordetail:Signed expiry time [Sat, 20 Nov 2021 02:46:49 GMT] has to be after signed start time [Mon, 29 Nov 2021 07:21:40 GMT]
```

**Workaround**

Run `job.refresh()` before running `job.get_results()`

**Comment by xinyi-joffre** [comment] 2023-11-02 01:07
Closing as duplicate of #181

**Closed by xinyi-joffre** 2023-11-02 01:07 UTC
Labels: bug, azure-quantum
